### ISSUE TITLE
[Header > search] 헤더 검색 text

### ISSUE THREAD

**Issue by devnunu** [NamNUNU/SNS_Project#5]
[내용]
일치하는 id 데이터를 데이터베이스에서 조회, 해당 프로필 화면 보여주기

[예상 소요시간]
6시간

[완료조건]
엔터 버튼 클릭시 input 필드 값을 받아서 서버에 데이터베이스 조회를 요청한 후 값들을 검색 페이지에 넘겨줌

**Comment by junhobaik** [comment]
b74aa21
Profile Part 에서 구현하였습니다.
